modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/MisterJulsen/TrafficCraft/issues"
license = "GNU General Public License v3.0"

[[mods]]
modId = "trafficcraft"
version = "${version}"
displayName = "TrafficCraft"
displayUrl="https://www.curseforge.com/minecraft/mc-mods/trafficcraft"
authors = "MrJulsen"
credits="This mod is inspired by Mapper's RoadStuff mod."
description = '''
A Minecraft mod that brings roads, traffic signs, traffic lights and much more to your Minecraft world. Build your own cities and roads according to your wishes. Feel free to join my Discord server for more information about my mods or to send bug reports, suggestions or to exchange with the community! https://discord.gg/AeSbNgvc7f
'''
logoFile = "mod_icon.png"

[[dependencies.trafficcraft]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trafficcraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.trafficcraft]]
modId = "dragonlib"
mandatory = true
versionRange = "[1.19.2-2.2.19,)"
ordering = "AFTER"
side = "BOTH"
