# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.2
release_channel = release
maven_group = de.mrjulsen.trafficcraft
archives_name = trafficcraft
enabled_platforms = fabric,neoforge
java_version = 21
datapack_version = 9

# Mod Info
display_name = TrafficCraft
authors = MrJulsen
description = A Minecraft mod that brings roads, traffic signs, traffic lights and much more to your Minecraft world. Build your own cities and roads according to your wishes. Feel free to join my Discord server for more information about my mods or to send bug reports, suggestions or to exchange with the community! https://discord.gg/AeSbNgvc7f
homepage = https://www.curseforge.com/minecraft/mc-mods/trafficcraft
issues = https://github.com/MisterJulsen/TrafficCraft/issues
source = https://github.com/MisterJulsen/TrafficCraft
license = GNU General Public License v3.0
icon = mod_icon.png
discord = https://discord.gg/AeSbNgvc7f

# Minecraft properties
minecraft_version = 1.21.1
parchment_minecraft_version = 1.21
parchment_version=2024.07.28
next_unsupported_minecraft_version=1.21.4

# Dependencies
architectury_api_version = 13.0.6
fabric_loader_version = 0.16.7
fabric_api_version = 0.102.0+1.21
neoforge_version = 21.1.72
neoforge_dependency_version = 21.0
neoforge_loader_version = 4

dragonlib_version=2.2.23
forge_config_api_port_version=21.1.1