# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx6G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.0
release_channel = beta
maven_group = de.mrjulsen.trafficcraft
archives_name = trafficcraft
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.18.2
parchment_version = 2022.11.06

# Dependencies
architectury_api_version = 4.12.94
fabric_loader_version = 0.15.11
fabric_api_version = 0.77.0+1.18.2
forge_version = 1.18.2-40.2.21

dragonlib_version=2.2.19
modmenu_version=3.2.5
forge_config_api_port_version=3.2.4