modLoader = "javafml"
loaderVersion = "[${neoforge_version_int},)"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]

modId = "${modid}"
version = "${version}"
displayName = "${display_name}"
displayUrl="${homepage}"
authors = "${authors}"
credits="This mod is inspired by Mapper's RoadStuff mod."
description = '''${description}'''
logoFile = "${icon}"

[[dependencies.${modid}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version_short},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},${next_unsupported_minecraft_version})"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modid}]]
modId = "dragonlib"
type = "required"
versionRange = "[${dragonlib_version},)"
ordering = "BEFORE"
side = "BOTH"

[[mixins]]
config = "${modid}.mixins.json"
